[
  {
    href: "/product-detail/astb001/",
    type: "Limited Edition",
    name: 'Ananas "Copy" Store Bag 001 - Black',
    id: "ASTB001",
    desription:
      "Gender – /Unisex/\nHoạ tiết – /Ananas – DiscoverYOU/\nChất liệu chính – Canvas 365GSM – (trượt nước)\nSize – /54 x 12 x 44 cm/",
    sizes: [" ", "Free"],
    colorsSame: [{ color: "#2d2c2f", href: "" }],
    color: "Black",
    price: "250.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/Pro_ASTB001_1.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/Pro_ASTB001_9.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Pro_ASTB001_3.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/Pro_ASTB001_4.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/Pro_ASTB001_6.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/Pro_ASTB001_7.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/Pro_ASTB001_8.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ath005/",
    type: "",
    name: "Trucker Hat - Be Positive",
    id: "ATH005",
    desription:
      "Trucker Hat - Be Positive màu Black/White đơn giản cùng artwork “Be Positive” mang nét tích cực của nhịp sống hiện đại. Với chất vải thun lạnh từ sợi Polyester có đệm mút và phần hậu dùng lưới mesh thông thoáng đặc trưng của Trucker Hat, đây chắc chắn là yếu tố ghi điểm cho những ngày quay cuồng, đầu bù tóc rối mà vẫn tự tin bứt phá chất tôi riêng biệt.",
    sizes: [" ", "free"],
    colorsSame: [{ color: "#f0f0ec", href: "" }],
    color: "Black/White",
    price: "275.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ATH005_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ATH005_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ATH005_3.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/abn001/",
    type: "",
    name: "Beanie Hat - Ananas Typo Box",
    id: "ABN001",
    desription:
      "Mũ Beanie màu Black đơn giản với artwork Ananas Typo Box nổi bật dễ nhận diện. Chiếc mũ có chất liệu mềm mịn, phom co giãn thoải mái. Đây chắc chắn là món phụ kiện không thể thiếu trong tủ đồ của bạn.",
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#656344", href: "/product-detail/abn002/" },
    ],
    color: "Black",
    price: "195.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ABN001_1-1-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ABN001_2.jpg" },
    ],
    soldout: true,
    category: "accessories",
  },
  {
    href: "/product-detail/abn002/",
    type: "",
    name: "Beanie Hat - Go Skate",
    id: "ABN002",
    desription:
      'Beanie - Go Skate đặc biệt ấn tượng với phối màu Olive cùng tem dệt artwork màu sắc, thể hiện năng lượng tích cực. Đây chắc chắn là chiếc mũ không thể thiếu mỗi lần gặp gỡ, đi trượt cùng "anh em".',
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#656344", href: "" },
      { color: "#2d2c2f", href: "/product-detail/abn001/" },
    ],
    color: "Olive",
    price: "195.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ABN002_1-1-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ABN002_2.jpg" },
    ],
    soldout: true,
    category: "accessories",
  },
  {
    href: "/product-detail/abh002/",
    type: "",
    name: "Bucket Hat - Go Skate",
    id: "ABH002",
    desription:
      'Chiếc Bucket Hat với phối màu Beige trung tính, thiết kế đơn giản nhằm thể hiện artwork màu sắc, nhấn mạnh thông điệp "Go Skate" mang nhiều năng lượng tích cực, thể hiện cái tôi riêng biệt. Phù hợp cho những người trẻ yêu thích sự va chạm, mong muốn vượt các thử thách bằng chính khả năng của mình.',
    sizes: [" ", "free"],
    colorsSame: [{ color: "#", href: "" }],
    color: "Beige",
    price: "285.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ABH002_1-2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ABH002_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ABH002_3.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ABH002_4.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/abp001/",
    type: "",
    name: "Basic Backpack - Ananas Typo Logo",
    id: "ABP001",
    desription:
      "Balo cực kì cơ bản, phù hợp đeo xuôi sau lưng hoặc đeo ngược phía trước. Với chất liệu được xử lí chống bám nước ở cả 2 lớp vải, các chi tiết nhỏ được chăm chút kĩ càng và vừa vặn với chiếc laptop 15.6''. Đây chắc chắn là một must have cho những ai yêu thích sự đơn giản mà hiệu quả.",
    sizes: [" ", "free"],
    colorsSame: [{ color: "#2d2c2f", href: "" }],
    color: "Black",
    price: "480.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ABP001_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ABP001_10-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ABP001_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ABP001_3.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ABP001_4.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ABP001_5.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ABP001_6.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ABP001_7.jpg" },
    ],
    soldout: true,
    category: "accessories",
  },
  {
    href: "/product-detail/ath001/",
    type: "Online Only",
    name: "Snapback Trucker Hat - Ananas Typo",
    id: "ATH001",
    desription:
      "Tông màu trắng đen cơ bản, thiết kế hiện đại với sự kết hợp của nhiều ưu điểm. Snapback Trucker Hat - Ananas Typo chính là must-have-item cùng bạn chinh phục mọi phối đồ từ đơn giản đến phức tạp.",
    sizes: [" ", "free"],
    colorsSame: [{ color: "#f0f0ec", href: "" }],
    color: "Black and White",
    price: "250.000 VND",
    images: [
      {
        href: "https://ananas.vn/wp-content/uploads/pro_snapback_ATH001_1.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_snapback_ATH001_2.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_snapback_ATH001_3.jpg",
      },
    ],
    soldout: true,
    category: "accessories",
  },
  {
    href: "/product-detail/ans010/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS010",
    desription:
      "Vớ ẩn hình có hoạ tiết đơn giản, gót nhựa trong cố định khó trượt. Tạo cảm giác thoải mái, đi như chân không và chắc chắn tàng hình khi mang trong giày.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "Ocean Depths",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS010_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/acs020/",
    type: "",
    name: "Crew Socks - Let It Be",
    id: "ACS020",
    desription:
      "Vớ cổ cao có chất liệu, công năng y chang vớ cổ trung nhưng ấm hơn và cao hơn một khúc. Bạn có thể mang nó trong mọi tình huống của cuộc sống (trừ lúc đi tắm và mang vớ đi giặt).",
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#f0f0ec", href: "/product-detail/acs021/" },
      { color: "#958d84", href: "/product-detail/acs022/" },
    ],
    color: "Jet Black",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/ACS020_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ACS020_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans024/",
    type: "",
    name: "Invisible Socks Pack - DiscoverYou",
    id: "ANS024",
    desription:
      "Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#f0f0ec", href: "/product-detail/ans023/" },
      { color: "#bbbcbc", href: "/product-detail/ans025/" },
      { color: "#bbbcbc", href: "/product-detail/ans026/" },
    ],
    color: "Black",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS024_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_1.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/alb009/",
    type: "",
    name: "Blank Shoelaces",
    id: "ALB009",
    desription:
      "Dây giày bản dẹp, màu White cơ bản. Sự lựa chọn đơn giản, phù hợp để mang với dáng Low Top, High Top.",
    sizes: [" ", "100", "115", "140"],
    colorsSame: [
      { color: "#f1f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/alb001/" },
      { color: "#f0f0ec", href: "/product-detail/alb002/" },
      { color: "#937e57", href: "/product-detail/alb003/" },
      { color: "#f05627", href: "/product-detail/alb004/" },
      { color: "#666766", href: "/product-detail/alb005/" },
      { color: "#009698", href: "/product-detail/alb006/" },
      { color: "#2d2c2f", href: "/product-detail/alb008/" },
      { color: "#ffc007", href: "/product-detail/alb010/" },
      { color: "#e3c7a6", href: "/product-detail/alb011/" },
      { color: "#00947d", href: "/product-detail/alb012/" },
      { color: "#a97a54", href: "/product-detail/alb013/" },
      { color: "#fc8b93", href: "/product-detail/alb014/" },
      { color: "#2e3561", href: "/product-detail/alb015/" },
      { color: "#d3e031", href: "/product-detail/alb016/" },
      { color: "#9c8bbc", href: "/product-detail/alb017/" },
    ],
    color: "White",
    price: "35.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB009_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB009_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB009_3.jpg" },
    ],
    soldout: true,
    category: "accessories",
  },
  {
    href: "/product-detail/alb016/",
    type: "",
    name: "Blank Shoelaces",
    id: "ALB016",
    desription:
      "Dây giày trơn màu Evening Primrose, dạng ống rỗng, thích hợp để thay mới hoặc mix màu cho đôi Low Top, High Top của bạn thêm khác biệt.",
    sizes: [" ", "100", "115", "140"],
    colorsSame: [
      { color: "#d3e031", href: "" },
      { color: "#ffc007", href: "/product-detail/alb010/" },
      { color: "#e3c7a6", href: "/product-detail/alb011/" },
      { color: "#00947d", href: "/product-detail/alb012/" },
      { color: "#a97a54", href: "/product-detail/alb013/" },
      { color: "#fc8b93", href: "/product-detail/alb014/" },
      { color: "#2e3561", href: "/product-detail/alb015/" },
      { color: "#9c8bbc", href: "/product-detail/alb017/" },
      { color: "#2d2c2f", href: "/product-detail/alb001/" },
      { color: "#f0f0ec", href: "/product-detail/alb002/" },
      { color: "#937e57", href: "/product-detail/alb003/" },
      { color: "#f05627", href: "/product-detail/alb004/" },
      { color: "#666766", href: "/product-detail/alb005/" },
      { color: "#009698", href: "/product-detail/alb006/" },
      { color: "#2d2c2f", href: "/product-detail/alb008/" },
      { color: "#f1f0ec", href: "/product-detail/alb009/" },
    ],
    color: "Evening Primrose",
    price: "35.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB016_1_Fix.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB016_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB016_3.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/acs001/",
    type: "",
    name: "Crew Socks - Ananas Typo",
    id: "ACS001",
    desription:
      "Vớ cổ cao có chất liệu, công năng y chang vớ cổ trung nhưng ấm hơn và cao hơn một khúc. Bạn có thể mang nó trong mọi tình huống của cuộc sống (trừ lúc đi tắm và mang vớ đi giặt).",
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#f05627", href: "/product-detail/acs003/" },
      { color: "#f0f0ec", href: "/product-detail/acs004/" },
      { color: "#2d2c2f", href: "/product-detail/acs005/" },
      { color: "#f0f0ec", href: "/product-detail/acs002/" },
    ],
    color: "Black",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/ACS001_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ACS001_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans011/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS011",
    desription:
      "Bộ 3 vớ tàng hình, nhiều màu nhiều lựa chọn. Một đi học, một đi làm, một đi chơi, thay phiên nhau tàng hình trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#f0f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS011_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/aas004/",
    type: "",
    name: "Anklet Socks - Ananas Typo",
    id: "AAS004",
    desription:
      'Vớ cổ trung có chất liệu và công năng như vớ vô hình nhưng lộ diện vừa đủ, kín kín hở hở, nhấn nhá sinh động nên chỉ phù hợp để mang từ sáng thứ "high" đến tối chủ nhật.',
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#2d2c2f", href: "/product-detail/aas001/" },
    ],
    color: "Jet Black",
    price: "85.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_sock_AAS004_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/bs01589.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans025/",
    type: "",
    name: "Invisible Socks Pack - DiscoverYou",
    id: "ANS025",
    desription:
      "Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#bbbcbc", href: "" },
      { color: "#f0f0ec", href: "/product-detail/ans023/" },
      { color: "#2d2c2f", href: "/product-detail/ans024/" },
      { color: "#bbbcbc", href: "/product-detail/ans026/" },
    ],
    color: "Grey",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS025_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_1.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans001-2/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS001",
    desription:
      "Vớ ẩn hình có hoạ tiết đơn giản, gót nhựa trong cố định khó trượt. Tạo cảm giác thoải mái, đi như chân không và chắc chắn tàng hình khi mang trong giày.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "Black",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS001_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/alb017/",
    type: "",
    name: "Blank Shoelaces",
    id: "ALB017",
    desription:
      "Dây giày trơn màu Sunlit Allium, dạng ống rỗng, thích hợp để thay mới hoặc mix màu cho đôi Low Top, High Top của bạn thêm khác biệt.",
    sizes: [" ", "100", "115", "140"],
    colorsSame: [
      { color: "#9c8bbc", href: "" },
      { color: "#ffc007", href: "/product-detail/alb010/" },
      { color: "#e3c7a6", href: "/product-detail/alb011/" },
      { color: "#00947d", href: "/product-detail/alb012/" },
      { color: "#a97a54", href: "/product-detail/alb013/" },
      { color: "#fc8b93", href: "/product-detail/alb014/" },
      { color: "#2e3561", href: "/product-detail/alb015/" },
      { color: "#d3e031", href: "/product-detail/alb016/" },
      { color: "#2d2c2f", href: "/product-detail/alb001/" },
      { color: "#f0f0ec", href: "/product-detail/alb002/" },
      { color: "#937e57", href: "/product-detail/alb003/" },
      { color: "#f05627", href: "/product-detail/alb004/" },
      { color: "#666766", href: "/product-detail/alb005/" },
      { color: "#009698", href: "/product-detail/alb006/" },
      { color: "#2d2c2f", href: "/product-detail/alb008/" },
      { color: "#f1f0ec", href: "/product-detail/alb009/" },
    ],
    color: "Sunlit Allium",
    price: "35.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB017_1_Fix.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB017_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB017_3.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/abc006/",
    type: "",
    name: "Baseball Cap - Live In The Moment",
    id: "ABC006",
    desription:
      "Dễ dàng mix & match với nhiều loại trang phục và phong cách thời trang khác nhau, mũ bóng chày có thiết kế cổ điển cùng hoạ tiết thêu đơn giản chính là món phụ kiện không thể thiếu trong tủ đồ nhà bạn.",
    sizes: [" ", "free"],
    colorsSame: [{ color: "#4580af", href: "" }],
    color: "Slate",
    price: "275.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/Pro_ABC006_1.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/Pro_ABC006_2.jpeg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans013/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS013",
    desription:
      "Bộ 3 vớ tàng hình, nhiều màu nhiều lựa chọn. Một đi học, một đi làm, một đi chơi, thay phiên nhau tàng hình trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#efc050", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS013_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans024/",
    type: "",
    name: "Invisible Socks Pack - DiscoverYou",
    id: "ANS024",
    desription:
      "Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#f0f0ec", href: "/product-detail/ans023/" },
      { color: "#bbbcbc", href: "/product-detail/ans025/" },
      { color: "#bbbcbc", href: "/product-detail/ans026/" },
    ],
    color: "Black",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS024_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_1.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/alb009/",
    type: "",
    name: "Blank Shoelaces",
    id: "ALB009",
    desription:
      "Dây giày bản dẹp, màu White cơ bản. Sự lựa chọn đơn giản, phù hợp để mang với dáng Low Top, High Top.",
    sizes: [" ", "100", "115", "140"],
    colorsSame: [
      { color: "#f1f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/alb001/" },
      { color: "#f0f0ec", href: "/product-detail/alb002/" },
      { color: "#937e57", href: "/product-detail/alb003/" },
      { color: "#f05627", href: "/product-detail/alb004/" },
      { color: "#666766", href: "/product-detail/alb005/" },
      { color: "#009698", href: "/product-detail/alb006/" },
      { color: "#2d2c2f", href: "/product-detail/alb008/" },
      { color: "#ffc007", href: "/product-detail/alb010/" },
      { color: "#e3c7a6", href: "/product-detail/alb011/" },
      { color: "#00947d", href: "/product-detail/alb012/" },
      { color: "#a97a54", href: "/product-detail/alb013/" },
      { color: "#fc8b93", href: "/product-detail/alb014/" },
      { color: "#2e3561", href: "/product-detail/alb015/" },
      { color: "#d3e031", href: "/product-detail/alb016/" },
      { color: "#9c8bbc", href: "/product-detail/alb017/" },
    ],
    color: "White",
    price: "35.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB009_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB009_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB009_3.jpg" },
    ],
    soldout: true,
    category: "accessories",
  },
  {
    href: "/product-detail/alb016/",
    type: "",
    name: "Blank Shoelaces",
    id: "ALB016",
    desription:
      "Dây giày trơn màu Evening Primrose, dạng ống rỗng, thích hợp để thay mới hoặc mix màu cho đôi Low Top, High Top của bạn thêm khác biệt.",
    sizes: [" ", "100", "115", "140"],
    colorsSame: [
      { color: "#d3e031", href: "" },
      { color: "#ffc007", href: "/product-detail/alb010/" },
      { color: "#e3c7a6", href: "/product-detail/alb011/" },
      { color: "#00947d", href: "/product-detail/alb012/" },
      { color: "#a97a54", href: "/product-detail/alb013/" },
      { color: "#fc8b93", href: "/product-detail/alb014/" },
      { color: "#2e3561", href: "/product-detail/alb015/" },
      { color: "#9c8bbc", href: "/product-detail/alb017/" },
      { color: "#2d2c2f", href: "/product-detail/alb001/" },
      { color: "#f0f0ec", href: "/product-detail/alb002/" },
      { color: "#937e57", href: "/product-detail/alb003/" },
      { color: "#f05627", href: "/product-detail/alb004/" },
      { color: "#666766", href: "/product-detail/alb005/" },
      { color: "#009698", href: "/product-detail/alb006/" },
      { color: "#2d2c2f", href: "/product-detail/alb008/" },
      { color: "#f1f0ec", href: "/product-detail/alb009/" },
    ],
    color: "Evening Primrose",
    price: "35.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB016_1_Fix.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB016_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB016_3.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/acs001/",
    type: "",
    name: "Crew Socks - Ananas Typo",
    id: "ACS001",
    desription:
      "Vớ cổ cao có chất liệu, công năng y chang vớ cổ trung nhưng ấm hơn và cao hơn một khúc. Bạn có thể mang nó trong mọi tình huống của cuộc sống (trừ lúc đi tắm và mang vớ đi giặt).",
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#f05627", href: "/product-detail/acs003/" },
      { color: "#f0f0ec", href: "/product-detail/acs004/" },
      { color: "#2d2c2f", href: "/product-detail/acs005/" },
      { color: "#f0f0ec", href: "/product-detail/acs002/" },
    ],
    color: "Black",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/ACS001_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ACS001_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans011/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS011",
    desription:
      "Bộ 3 vớ tàng hình, nhiều màu nhiều lựa chọn. Một đi học, một đi làm, một đi chơi, thay phiên nhau tàng hình trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#f0f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS011_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/aas004/",
    type: "",
    name: "Anklet Socks - Ananas Typo",
    id: "AAS004",
    desription:
      'Vớ cổ trung có chất liệu và công năng như vớ vô hình nhưng lộ diện vừa đủ, kín kín hở hở, nhấn nhá sinh động nên chỉ phù hợp để mang từ sáng thứ "high" đến tối chủ nhật.',
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#2d2c2f", href: "/product-detail/aas001/" },
    ],
    color: "Jet Black",
    price: "85.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_sock_AAS004_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/bs01589.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans025/",
    type: "",
    name: "Invisible Socks Pack - DiscoverYou",
    id: "ANS025",
    desription:
      "Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#bbbcbc", href: "" },
      { color: "#f0f0ec", href: "/product-detail/ans023/" },
      { color: "#2d2c2f", href: "/product-detail/ans024/" },
      { color: "#bbbcbc", href: "/product-detail/ans026/" },
    ],
    color: "Grey",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS025_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_1.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans001-2/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS001",
    desription:
      "Vớ ẩn hình có hoạ tiết đơn giản, gót nhựa trong cố định khó trượt. Tạo cảm giác thoải mái, đi như chân không và chắc chắn tàng hình khi mang trong giày.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "Black",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS001_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/alb017/",
    type: "",
    name: "Blank Shoelaces",
    id: "ALB017",
    desription:
      "Dây giày trơn màu Sunlit Allium, dạng ống rỗng, thích hợp để thay mới hoặc mix màu cho đôi Low Top, High Top của bạn thêm khác biệt.",
    sizes: [" ", "100", "115", "140"],
    colorsSame: [
      { color: "#9c8bbc", href: "" },
      { color: "#ffc007", href: "/product-detail/alb010/" },
      { color: "#e3c7a6", href: "/product-detail/alb011/" },
      { color: "#00947d", href: "/product-detail/alb012/" },
      { color: "#a97a54", href: "/product-detail/alb013/" },
      { color: "#fc8b93", href: "/product-detail/alb014/" },
      { color: "#2e3561", href: "/product-detail/alb015/" },
      { color: "#d3e031", href: "/product-detail/alb016/" },
      { color: "#2d2c2f", href: "/product-detail/alb001/" },
      { color: "#f0f0ec", href: "/product-detail/alb002/" },
      { color: "#937e57", href: "/product-detail/alb003/" },
      { color: "#f05627", href: "/product-detail/alb004/" },
      { color: "#666766", href: "/product-detail/alb005/" },
      { color: "#009698", href: "/product-detail/alb006/" },
      { color: "#2d2c2f", href: "/product-detail/alb008/" },
      { color: "#f1f0ec", href: "/product-detail/alb009/" },
    ],
    color: "Sunlit Allium",
    price: "35.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB017_1_Fix.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB017_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB017_3.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/abc006/",
    type: "",
    name: "Baseball Cap - Live In The Moment",
    id: "ABC006",
    desription:
      "Dễ dàng mix & match với nhiều loại trang phục và phong cách thời trang khác nhau, mũ bóng chày có thiết kế cổ điển cùng hoạ tiết thêu đơn giản chính là món phụ kiện không thể thiếu trong tủ đồ nhà bạn.",
    sizes: [" ", "free"],
    colorsSame: [{ color: "#4580af", href: "" }],
    color: "Slate",
    price: "275.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/Pro_ABC006_1.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/Pro_ABC006_2.jpeg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans013/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS013",
    desription:
      "Bộ 3 vớ tàng hình, nhiều màu nhiều lựa chọn. Một đi học, một đi làm, một đi chơi, thay phiên nhau tàng hình trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#efc050", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS013_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans026/",
    type: "",
    name: "Invisible Socks Pack - DiscoverYou",
    id: "ANS026",
    desription:
      "Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#bbbcbc", href: "" },
      { color: "#f0f0ec", href: "/product-detail/ans023/" },
      { color: "#2d2c2f", href: "/product-detail/ans024/" },
      { color: "#bbbcbc", href: "/product-detail/ans025/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS026_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_1.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans002-2/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS002",
    desription:
      "Vớ ẩn hình có hoạ tiết đơn giản, gót nhựa trong cố định khó trượt. Tạo cảm giác thoải mái, đi như chân không và chắc chắn tàng hình khi mang trong giày.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "Black",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS002_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/abc007/",
    type: "",
    name: "Baseball Cap - Be Positive",
    id: "ABC007",
    desription:
      "Dễ dàng mix & match với nhiều loại trang phục và phong cách thời trang khác nhau, mũ bóng chày có thiết kế cổ điển cùng hoạ tiết thêu đơn giản chính là món phụ kiện không thể thiếu trong tủ đồ nhà bạn.",
    sizes: [" ", "free"],
    colorsSame: [{ color: "#bfaa80", href: "" }],
    color: "Forest",
    price: "275.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/Pro_ABC007_1.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/Pro_ABC007_2.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/Pro_ABC007_3.jpeg" },
    ],
    soldout: true,
    category: "accessories",
  },
  {
    href: "/product-detail/ans015/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS015",
    desription:
      "Bộ 3 vớ tàng hình, nhiều màu nhiều lựa chọn. Một đi học, một đi làm, một đi chơi, thay phiên nhau tàng hình trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#253659", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS015_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/alb001/",
    type: "",
    name: "Blank Shoelaces",
    id: "ALB001",
    desription:
      "Dây giày trơn màu Black, dạng ống rỗng, thích hợp để thay mới hoặc mix màu cho đôi Low Top, High Top của bạn thêm khác biệt.",
    sizes: [" ", "100", "115", "140"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#f0f0ec", href: "/product-detail/alb002/" },
      { color: "#937e57", href: "/product-detail/alb003/" },
      { color: "#f05627", href: "/product-detail/alb004/" },
      { color: "#666766", href: "/product-detail/alb005/" },
      { color: "#009698", href: "/product-detail/alb006/" },
      { color: "#2d2c2f", href: "/product-detail/alb008/" },
      { color: "#f1f0ec", href: "/product-detail/alb009/" },
      { color: "#ffc007", href: "/product-detail/alb010/" },
      { color: "#e3c7a6", href: "/product-detail/alb011/" },
      { color: "#00947d", href: "/product-detail/alb012/" },
      { color: "#a97a54", href: "/product-detail/alb013/" },
      { color: "#fc8b93", href: "/product-detail/alb014/" },
      { color: "#2e3561", href: "/product-detail/alb015/" },
      { color: "#9c8bbc", href: "/product-detail/alb017/" },
      { color: "#d3e031", href: "/product-detail/alb016/" },
    ],
    color: "Black",
    price: "35.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB001_1-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB001_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB001_3.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/acs002/",
    type: "",
    name: "Crew Socks - Ananas Typo",
    id: "ACS002",
    desription:
      "Vớ cổ cao, cao hơn vớ cổ trung một khúc, tăng phần cổ chân tạo độ ấm vừa phải. Thích hợp mang cho mọi tình huống của cuộc sống.",
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#f0f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/acs001/" },
      { color: "#f05627", href: "/product-detail/acs003/" },
      { color: "#f0f0ec", href: "/product-detail/acs004/" },
      { color: "#2d2c2f", href: "/product-detail/acs005/" },
    ],
    color: "White",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ACS002_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ACS002_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans003/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS003",
    desription:
      "Vớ ẩn hình có hoạ tiết đơn giản, gót nhựa trong cố định khó trượt. Tạo cảm giác thoải mái, đi như chân không và chắc chắn tàng hình khi mang trong giày.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#bbbcbc", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "Grey",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS003_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/acs009/",
    type: "",
    name: "Crew Socks - Ananas Typo",
    id: "ACS009",
    desription:
      "Vớ cổ cao có chất liệu, công năng y chang vớ cổ cổ trung nhưng ấm hơn và cao hơn một khúc. Bạn có thể mang nó trong mọi tình huống của cuộc sống (trừ lúc đi tắm và mang vớ đi giặt).",
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#f0f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/acs010/" },
    ],
    color: "Snow White",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/ACS009_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ACS009_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans017/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS017",
    desription:
      "Bộ 3 vớ tàng hình, nhiều màu nhiều lựa chọn. Một đi học, một đi làm, một đi chơi, thay phiên nhau tàng hình trong đôi giày của bạn.",
    sizes: [" ", "S"],
    colorsSame: [
      { color: "#f0f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS017_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans013/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS013",
    desription:
      "Bộ 3 vớ tàng hình, nhiều màu nhiều lựa chọn. Một đi học, một đi làm, một đi chơi, thay phiên nhau tàng hình trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#efc050", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS013_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans026/",
    type: "",
    name: "Invisible Socks Pack - DiscoverYou",
    id: "ANS026",
    desription:
      "Bộ 3 vớ màu cơ bản, tàng hình, ít thấy khi mang thay phiên trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#bbbcbc", href: "" },
      { color: "#f0f0ec", href: "/product-detail/ans023/" },
      { color: "#2d2c2f", href: "/product-detail/ans024/" },
      { color: "#bbbcbc", href: "/product-detail/ans025/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS026_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_1.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans002-2/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS002",
    desription:
      "Vớ ẩn hình có hoạ tiết đơn giản, gót nhựa trong cố định khó trượt. Tạo cảm giác thoải mái, đi như chân không và chắc chắn tàng hình khi mang trong giày.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "Black",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS002_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/abc007/",
    type: "",
    name: "Baseball Cap - Be Positive",
    id: "ABC007",
    desription:
      "Dễ dàng mix & match với nhiều loại trang phục và phong cách thời trang khác nhau, mũ bóng chày có thiết kế cổ điển cùng hoạ tiết thêu đơn giản chính là món phụ kiện không thể thiếu trong tủ đồ nhà bạn.",
    sizes: [" ", "free"],
    colorsSame: [{ color: "#bfaa80", href: "" }],
    color: "Forest",
    price: "275.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/Pro_ABC007_1.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/Pro_ABC007_2.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/Pro_ABC007_3.jpeg" },
    ],
    soldout: true,
    category: "accessories",
  },
  {
    href: "/product-detail/ans015/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS015",
    desription:
      "Bộ 3 vớ tàng hình, nhiều màu nhiều lựa chọn. Một đi học, một đi làm, một đi chơi, thay phiên nhau tàng hình trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#253659", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS015_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/alb001/",
    type: "",
    name: "Blank Shoelaces",
    id: "ALB001",
    desription:
      "Dây giày trơn màu Black, dạng ống rỗng, thích hợp để thay mới hoặc mix màu cho đôi Low Top, High Top của bạn thêm khác biệt.",
    sizes: [" ", "100", "115", "140"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#f0f0ec", href: "/product-detail/alb002/" },
      { color: "#937e57", href: "/product-detail/alb003/" },
      { color: "#f05627", href: "/product-detail/alb004/" },
      { color: "#666766", href: "/product-detail/alb005/" },
      { color: "#009698", href: "/product-detail/alb006/" },
      { color: "#2d2c2f", href: "/product-detail/alb008/" },
      { color: "#f1f0ec", href: "/product-detail/alb009/" },
      { color: "#ffc007", href: "/product-detail/alb010/" },
      { color: "#e3c7a6", href: "/product-detail/alb011/" },
      { color: "#00947d", href: "/product-detail/alb012/" },
      { color: "#a97a54", href: "/product-detail/alb013/" },
      { color: "#fc8b93", href: "/product-detail/alb014/" },
      { color: "#2e3561", href: "/product-detail/alb015/" },
      { color: "#9c8bbc", href: "/product-detail/alb017/" },
      { color: "#d3e031", href: "/product-detail/alb016/" },
    ],
    color: "Black",
    price: "35.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB001_1-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB001_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB001_3.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/acs002/",
    type: "",
    name: "Crew Socks - Ananas Typo",
    id: "ACS002",
    desription:
      "Vớ cổ cao, cao hơn vớ cổ trung một khúc, tăng phần cổ chân tạo độ ấm vừa phải. Thích hợp mang cho mọi tình huống của cuộc sống.",
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#f0f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/acs001/" },
      { color: "#f05627", href: "/product-detail/acs003/" },
      { color: "#f0f0ec", href: "/product-detail/acs004/" },
      { color: "#2d2c2f", href: "/product-detail/acs005/" },
    ],
    color: "White",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ACS002_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ACS002_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans003/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS003",
    desription:
      "Vớ ẩn hình có hoạ tiết đơn giản, gót nhựa trong cố định khó trượt. Tạo cảm giác thoải mái, đi như chân không và chắc chắn tàng hình khi mang trong giày.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#bbbcbc", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "Grey",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS003_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/acs009/",
    type: "",
    name: "Crew Socks - Ananas Typo",
    id: "ACS009",
    desription:
      "Vớ cổ cao có chất liệu, công năng y chang vớ cổ cổ trung nhưng ấm hơn và cao hơn một khúc. Bạn có thể mang nó trong mọi tình huống của cuộc sống (trừ lúc đi tắm và mang vớ đi giặt).",
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#f0f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/acs010/" },
    ],
    color: "Snow White",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/ACS009_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ACS009_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans017/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS017",
    desription:
      "Bộ 3 vớ tàng hình, nhiều màu nhiều lựa chọn. Một đi học, một đi làm, một đi chơi, thay phiên nhau tàng hình trong đôi giày của bạn.",
    sizes: [" ", "S"],
    colorsSame: [
      { color: "#f0f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS017_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/alb002/",
    type: "",
    name: "Blank Shoelaces",
    id: "ALB002",
    desription:
      "Dây giày trơn màu White, dạng ống rỗng, thích hợp để thay mới hoặc mix màu cho đôi Low Top, High Top của bạn thêm khác biệt.",
    sizes: [" ", "100", "115", "140"],
    colorsSame: [
      { color: "#f0f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/alb001/" },
      { color: "#937e57", href: "/product-detail/alb003/" },
      { color: "#f05627", href: "/product-detail/alb004/" },
      { color: "#666766", href: "/product-detail/alb005/" },
      { color: "#009698", href: "/product-detail/alb006/" },
      { color: "#2d2c2f", href: "/product-detail/alb008/" },
      { color: "#f1f0ec", href: "/product-detail/alb009/" },
      { color: "#ffc007", href: "/product-detail/alb010/" },
      { color: "#e3c7a6", href: "/product-detail/alb011/" },
      { color: "#00947d", href: "/product-detail/alb012/" },
      { color: "#a97a54", href: "/product-detail/alb013/" },
      { color: "#fc8b93", href: "/product-detail/alb014/" },
      { color: "#2e3561", href: "/product-detail/alb015/" },
      { color: "#d3e031", href: "/product-detail/alb016/" },
      { color: "#9c8bbc", href: "/product-detail/alb017/" },
    ],
    color: "White",
    price: "35.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB002_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB002_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB002_3.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/aas001/",
    type: "",
    name: "Anklet Socks - Ananas Typo",
    id: "AAS001",
    desription:
      "Vớ cổ trung màu Black cơ bản, kiểu dáng thường ngày. Tích hợp khả năng ôm trọn bàn chân với phần có độ ôm cố định, tạo cảm giác êm ái thoải mái.",
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#2d2c2f", href: "/product-detail/aas004/" },
    ],
    color: "Black",
    price: "85.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_AAS001_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AAS001_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans004/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS004",
    desription:
      "Vớ ẩn hình có hoạ tiết đơn giản, gót nhựa trong cố định khó trượt. Tạo cảm giác thoải mái, đi như chân không và chắc chắn tàng hình khi mang trong giày.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#f0f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "White",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS004_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/acs010/",
    type: "",
    name: "Crew Socks - Ananas Typo",
    id: "ACS010",
    desription:
      "Vớ cổ cao có chất liệu, công năng y chang vớ cổ cổ trung nhưng ấm hơn và cao hơn một khúc. Bạn có thể mang nó trong mọi tình huống của cuộc sống (trừ lúc đi tắm và mang vớ đi giặt).",
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#f0f0ec", href: "/product-detail/acs009/" },
    ],
    color: "Jet Black",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/ACS010_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ACS010_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans018/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS018",
    desription:
      "Bộ 3 vớ tàng hình, nhiều màu nhiều lựa chọn. Một đi học, một đi làm, một đi chơi, thay phiên nhau tàng hình trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#bbbcbc", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS018_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/alb003/",
    type: "",
    name: "Blank Shoelaces",
    id: "ALB003",
    desription:
      "Dây giày bản dẹp, đặc biệt nổi bật ở phần màu sắc. Phù hợp để tạo điểm nhấn mới mẻ, vừa phá cách trên chính đôi giày của bạn.",
    sizes: [" ", "100", "115", "140"],
    colorsSame: [
      { color: "#937e57", href: "" },
      { color: "#2d2c2f", href: "/product-detail/alb001/" },
      { color: "#f0f0ec", href: "/product-detail/alb002/" },
      { color: "#f05627", href: "/product-detail/alb004/" },
      { color: "#666766", href: "/product-detail/alb005/" },
      { color: "#009698", href: "/product-detail/alb006/" },
      { color: "#2d2c2f", href: "/product-detail/alb008/" },
      { color: "#f1f0ec", href: "/product-detail/alb009/" },
      { color: "#ffc007", href: "/product-detail/alb010/" },
      { color: "#e3c7a6", href: "/product-detail/alb011/" },
      { color: "#00947d", href: "/product-detail/alb012/" },
      { color: "#a97a54", href: "/product-detail/alb013/" },
      { color: "#fc8b93", href: "/product-detail/alb014/" },
      { color: "#2e3561", href: "/product-detail/alb015/" },
      { color: "#d3e031", href: "/product-detail/alb016/" },
      { color: "#9c8bbc", href: "/product-detail/alb017/" },
    ],
    color: "Antique Bronze",
    price: "35.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/ALB003_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ALB003_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ALB003_3.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/alb010/",
    type: "",
    name: "Blank Shoelaces",
    id: "ALB010",
    desription:
      "Dây giày trơn màu Spectra Yellow, dạng ống rỗng, thích hợp để thay mới hoặc mix màu cho đôi Low Top, High Top của bạn thêm khác biệt.",
    sizes: [" ", "100", "115", "140"],
    colorsSame: [
      { color: "#ffc007", href: "" },
      { color: "#e3c7a6", href: "/product-detail/alb011/" },
      { color: "#00947d", href: "/product-detail/alb012/" },
      { color: "#a97a54", href: "/product-detail/alb013/" },
      { color: "#fc8b93", href: "/product-detail/alb014/" },
      { color: "#2e3561", href: "/product-detail/alb015/" },
      { color: "#d3e031", href: "/product-detail/alb016/" },
      { color: "#9c8bbc", href: "/product-detail/alb017/" },
      { color: "#2d2c2f", href: "/product-detail/alb001/" },
      { color: "#f0f0ec", href: "/product-detail/alb002/" },
      { color: "#937e57", href: "/product-detail/alb003/" },
      { color: "#f05627", href: "/product-detail/alb004/" },
      { color: "#666766", href: "/product-detail/alb005/" },
      { color: "#009698", href: "/product-detail/alb006/" },
      { color: "#2d2c2f", href: "/product-detail/alb008/" },
      { color: "#f1f0ec", href: "/product-detail/alb009/" },
    ],
    color: "Spectra Yellow",
    price: "35.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB010_1_Fix.jpeg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB010_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_ALB010_3.jpg" },
    ],
    soldout: true,
    category: "accessories",
  },
  {
    href: "/product-detail/ans005/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS005",
    desription:
      "Vớ ẩn hình có hoạ tiết đơn giản, gót nhựa trong cố định khó trượt. Tạo cảm giác thoải mái, đi như chân không và chắc chắn tàng hình khi mang trong giày.",
    sizes: [" ", "S"],
    colorsSame: [
      { color: "#f0f0ec", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#596236", href: "/product-detail/ans022/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
    ],
    color: "White",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS005_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/acs003/",
    type: "",
    name: "Crew Socks - Ananas Typo",
    id: "ACS003",
    desription:
      "Vớ cổ cao có chất liệu, công năng y chang vớ cổ cổ trung nhưng ấm hơn và cao hơn một khúc. Bạn có thể mang nó trong mọi tình huống của cuộc sống (trừ lúc đi tắm và mang vớ đi giặt).",
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#f05627", href: "" },
      { color: "#f0f0ec", href: "/product-detail/acs004/" },
      { color: "#2d2c2f", href: "/product-detail/acs005/" },
      { color: "#2d2c2f", href: "/product-detail/acs001/" },
      { color: "#f0f0ec", href: "/product-detail/acs002/" },
    ],
    color: "Red Orange",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/ACS003_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ACS003_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/ans019/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS019",
    desription:
      "Bộ 3 vớ tàng hình, nhiều màu nhiều lựa chọn. Một đi học, một đi làm, một đi chơi, thay phiên nhau tàng hình trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#9b2335", href: "/product-detail/ans020/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS019_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
  {
    href: "/product-detail/acs004/",
    type: "",
    name: "Crew Socks - Ananas Typo",
    id: "ACS004",
    desription:
      "Vớ cổ cao có chất liệu, công năng y chang vớ cổ cổ trung nhưng ấm hơn và cao hơn một khúc. Bạn có thể mang nó trong mọi tình huống của cuộc sống (trừ lúc đi tắm và mang vớ đi giặt).",
    sizes: [" ", "free"],
    colorsSame: [
      { color: "#f0f0ec", href: "" },
      { color: "#f05627", href: "/product-detail/acs003/" },
      { color: "#2d2c2f", href: "/product-detail/acs005/" },
      { color: "#2d2c2f", href: "/product-detail/acs001/" },
      { color: "#f0f0ec", href: "/product-detail/acs002/" },
    ],
    color: "Snow White",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/ACS004_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/ACS004_2.jpg" },
    ],
    soldout: true,
    category: "accessories",
  },
  {
    href: "/product-detail/ans020/",
    type: "",
    name: "Invisible Socks Pack - Ananas Typo",
    id: "ANS020",
    desription:
      "Bộ 3 vớ tàng hình, nhiều màu nhiều lựa chọn. Một đi học, một đi làm, một đi chơi, thay phiên nhau tàng hình trong đôi giày của bạn.",
    sizes: [" ", "M", "S"],
    colorsSame: [
      { color: "#9b2335", href: "" },
      { color: "#2d2c2f", href: "/product-detail/ans001-2/" },
      { color: "#2d2c2f", href: "/product-detail/ans002-2/" },
      { color: "#bbbcbc", href: "/product-detail/ans003/" },
      { color: "#f0f0ec", href: "/product-detail/ans004/" },
      { color: "#f0f0ec", href: "/product-detail/ans005/" },
      { color: "#253659", href: "/product-detail/ans006/" },
      { color: "#596236", href: "/product-detail/ans007/" },
      { color: "#efc050", href: "/product-detail/ans008/" },
      { color: "#d0e7e6", href: "/product-detail/ans009/" },
      { color: "#f0f0ec", href: "/product-detail/ans011/" },
      { color: "#efc050", href: "/product-detail/ans013/" },
      { color: "#253659", href: "/product-detail/ans015/" },
      { color: "#f0f0ec", href: "/product-detail/ans017/" },
      { color: "#bbbcbc", href: "/product-detail/ans018/" },
      { color: "#2d2c2f", href: "/product-detail/ans019/" },
      { color: "#ef5327", href: "/product-detail/ans021/" },
      { color: "#596236", href: "/product-detail/ans022/" },
    ],
    color: "3 Colors",
    price: "95.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_ANS020_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/Detail_2.jpg" },
    ],
    soldout: false,
    category: "accessories",
  },
];
