[
  {
    href: "/product-detail/agt0020/",
    type: "Limited Edition",
    name: "Graphic Pocket Tee - Doraemon 50 Years",
    id: "AGT0020",
    desription:
      "Ananas Graphic Tee sở hữu phom dáng rộng thoải mái với chất vải 100% cotton dày vừa phải. Kết hợp chi tiết từ bộ truyện Doraemon cùng Typo đặc trưng kỉ niệm 50 năm tạo nên chiếc Pocket cá tính bên ngực trái. Chiếc áo là mảnh ghép phù hợp cho những bạn yêu thích Doraemon và muốn lưu dấu cột mốc đặc biệt này.",
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [{ color: "#f1f0ec", href: "" }],
    color: "Cloud Dancer",
    price: "390.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_AGT0020_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AGT0020_2-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AGT0020_3-2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AGT0020_4-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AGT0020_5-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AGT0020_6-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AGT0020_7-1.jpg" },
    ],
    soldout: true,
    category: "top",
  },
  {
    href: "/product-detail/aho0010/",
    type: "Limited Edition",
    name: "Doraemon 50 Years Hoodie",
    id: "AHO0010",
    desription:
      "Chiếc Hoodie màu Black căn bản sở hữu nhiều graphic truyện tranh Doraemon ẩn giấu. Điểm nhấn đặc biệt từ logo Doraemon phiên bản tiếng Nhật đặc trưng với hiệu ứng ép nổi 3D độc đáo và chiếc túi trước bụng, tuy không phải túi thần kì nhưng sẽ mang đến cho bạn những ứng dụng bất ngờ.",
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [{ color: "#2d2c2f", href: "" }],
    color: "Black",
    price: "590.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_AHO0010_1-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AHO0010_2-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AHO0010_3-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AHO0010_4-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AHO0010_5-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AHO0010_6-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AHO0010_7-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AHO0010_8-1.jpg" },
    ],
    soldout: true,
    category: "top",
  },
  {
    href: "/product-detail/asw0011/",
    type: "",
    name: "Ananas Typo Sweatshirt",
    id: "ASW0011",
    desription:
      'Thiết kế cơ bản với chất liệu nỉ cao cấp được lựa chọn kĩ lưỡng để phù hợp với thời tiết Sài Gòn, "Ananas Typo Sweatshirt" sẽ tạo nên một outfit đơn giản nhưng sporty "hợp thời", giữ ấm vừa phải nhưng không bí bức. Đây sẽ là một chiếc áo nằm trong danh sách must have đến từ Ananas trong dịp cuối năm.',
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [{ color: "#f0f0ec", href: "" }],
    color: "White",
    price: "480.000 VND",
    images: [
      {
        href: "https://ananas.vn/wp-content/uploads/pro_sweater_ASW0011_1.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_sweater_ASW0011_2.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_sweater_ASW0011_3.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_sweater_ASW0011_4.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_sweater_ASW0011_5.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_sweater_ASW0011_6.jpg",
      },
    ],
    soldout: false,
    category: "top",
  },
  {
    href: "/product-detail/agt0003/",
    type: "",
    name: "Hiphop Graphic Tee - Discover Ananas",
    id: "AGT0003",
    desription:
      "Streetwear nói chung và thời trang Hiphop nói riêng không bao giờ thiếu đi những chiếc Graphic Tee nổi bật với cổ tròn ôm gọn, tay lỡ và phom áo rộng linh hoạt. Kết hợp cùng họa tiết Discover Ananas ở trước và sau, Hiphop Graphic Tee sẽ là một mảnh ghép không tồi giúp bạn có bộ outfit thú vị và khẳng định cá tính riêng của bản thân.",
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [{ color: "#836b4f", href: "" }],
    color: "Ermine",
    price: "365.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_agt0003_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AGT0003_2-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AGT0003_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AGT0003_3.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_AGT0003_4.jpg" },
    ],
    soldout: false,
    category: "top",
  },
  {
    href: "/product-detail/agt0010/",
    type: "",
    name: "Hiphop Graphic Tee - Ananas Symbol",
    id: "AGT0010",
    desription:
      "Streetwear nói chung và thời trang Hiphop nói riêng không bao giờ thiếu đi những chiếc Graphic Tee nổi bật với cổ tròn ôm gọn, tay lỡ và phom áo rộng linh hoạt. Kết hợp cùng họa tiết Discover Ananas ở trước và sau, Hiphop Graphic Tee sẽ là một mảnh ghép không tồi giúp bạn có bộ outfit thú vị và khẳng định cá tính riêng của bản thân.",
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#d71e18", href: "/product-detail/agt0009/" },
    ],
    color: "Black",
    price: "365.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/AGT0010_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0010_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0010_3.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0010_4.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0010_5.jpg" },
    ],
    soldout: false,
    category: "top",
  },
  {
    href: "/product-detail/agt0011/",
    type: "",
    name: "Hiphop Graphic Tee - Est. '17 Ananas",
    id: "AGT0011",
    desription:
      "Streetwear nói chung và thời trang Hiphop nói riêng không bao giờ thiếu đi những chiếc Graphic Tee nổi bật với cổ tròn ôm gọn, tay lỡ và phom áo rộng linh hoạt. Kết hợp cùng họa tiết Ananas Est. 2017, Hiphop Graphic Tee sẽ là một mảnh ghép không tồi giúp bạn có bộ outfit thú vị và khẳng định cá tính riêng của bản thân. Est. '17 Ananas cũng là chiếc áo đơn giản nhất so với các mẫu cùng dòng Graphic Tee, do đó lại càng thêm phù hợp cho những ai tìm kiếm sự phá cách vừa đủ, không cần quá nổi bật.",
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [
      { color: "#2d2c2f", href: "" },
      { color: "#836b4f", href: "/product-detail/agt0012/" },
    ],
    color: "Black",
    price: "350.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/AGT0011_1-1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0011_3.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0011_4.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0011_5.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0011_2-1.jpg" },
    ],
    soldout: false,
    category: "top",
  },
  {
    href: "/product-detail/agt0006/",
    type: "",
    name: "Hiphop Graphic Tee - Outline Typo",
    id: "AGT0006",
    desription:
      "Streetwear nói chung và thời trang Hiphop nói riêng không bao giờ thiếu đi những chiếc Graphic Tee nổi bật với cổ tròn ôm gọn, tay lỡ và phom áo rộng linh hoạt. Kết hợp cùng họa tiết Ananas Typo biến tấu lạ mắt cùng dòng chữ Discover Ananas sau cổ, Hiphop Graphic Tee sẽ là một mảnh ghép không tồi giúp bạn có bộ outfit thú vị và khẳng định cá tính riêng của bản thân.",
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [{ color: "#2d2c2f", href: "" }],
    color: "Black",
    price: "350.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/AGT0006_5.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGt0006_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0006_3.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0006_4.jpg" },
    ],
    soldout: false,
    category: "top",
  },
  {
    href: "/product-detail/agt0012/",
    type: "",
    name: "Hiphop Graphic Tee - Est. 17' Ananas",
    id: "AGT0012",
    desription:
      "Streetwear nói chung và thời trang Hiphop nói riêng không bao giờ thiếu đi những chiếc Graphic Tee nổi bật với cổ tròn ôm gọn, tay lỡ và phom áo rộng linh hoạt. Kết hợp cùng họa tiết Ananas Est. 2017, Hiphop Graphic Tee sẽ là một mảnh ghép không tồi giúp bạn có bộ outfit thú vị và khẳng định cá tính riêng của bản thân. Est. '17 Ananas cũng là chiếc áo đơn giản nhất so với các mẫu cùng dòng Graphic Tee, do đó lại càng thêm phù hợp cho những ai tìm kiếm sự phá cách vừa đủ, không cần quá nổi bật.",
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [
      { color: "#836b4f", href: "" },
      { color: "#2d2c2f", href: "/product-detail/agt0011/" },
    ],
    color: "Ermine",
    price: "350.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/AGT0012_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0012_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0012_3.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0012_4.jpg" },
    ],
    soldout: false,
    category: "top",
  },
  {
    href: "/product-detail/agt0009/",
    type: "",
    name: "Hiphop Graphic Tee - Ananas Symbol",
    id: "AGT0009",
    desription:
      "Streetwear nói chung và thời trang Hiphop nói riêng không bao giờ thiếu đi những chiếc Graphic Tee nổi bật với cổ tròn ôm gọn, tay lỡ và phom áo rộng linh hoạt. Kết hợp cùng họa tiết trái Dứa sau lưng áo, Hiphop Graphic Tee sẽ là một mảnh ghép không tồi giúp bạn có bộ outfit thú vị và khẳng định cá tính riêng của bản thân.",
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [
      { color: "#d71e18", href: "" },
      { color: "#2d2c2f", href: "/product-detail/agt0010/" },
    ],
    color: "Ketchup",
    price: "365.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/AGT0009_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0009_3.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0009_4.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0009_5.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/AGT0009_6.jpg" },
    ],
    soldout: false,
    category: "top",
  },
  {
    href: "/product-detail/abt00010/",
    type: "",
    name: "Basic Tee - Ananas Cropped Symbol",
    id: "ABT00010",
    desription:
      "Áo thun trơn, ngắn tay, cổ tròn cùng họa tiết Ananas Cropped Symbol in trên ngực áo. Phom dáng cổ điển và linh hoạt, thích hợp cho cả Nam và Nữ.",
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [
      { color: "#efad00", href: "" },
      { color: "#645d54", href: "/product-detail/abt00011/" },
    ],
    color: "Old Gold",
    price: "269.000 VND",
    images: [
      {
        href: "https://ananas.vn/wp-content/uploads/pro_basictee_ABT00011_1.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_basictee_ABT00011_2.jpg",
      },
    ],
    soldout: false,
    category: "top",
  },
  {
    href: "/product-detail/abt00011/",
    type: "Online Only",
    name: "Basic Tee - Ananas Cropped Symbol",
    id: "ABT00011",
    desription:
      "Áo thun trơn, ngắn tay, cổ tròn cùng họa tiết Ananas Cropped Symbol in trên ngực áo. Phom dáng cổ điển và linh hoạt, thích hợp cho cả Nam và Nữ.",
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [
      { color: "#645d54", href: "" },
      { color: "#efad00", href: "/product-detail/abt00010/" },
    ],
    color: "Bungee Cord",
    price: "269.000 VND",
    images: [
      {
        href: "https://ananas.vn/wp-content/uploads/pro_basictee_ABT00011_1-1.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_basictee_ABT00011_2-1.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_basictee_ABT00011_3.jpg",
      },
    ],
    soldout: false,
    category: "top",
  },
  {
    href: "/product-detail/abt00017/",
    type: "Online Only",
    name: "Basic Tee - Ananas Graphic",
    id: "ABT00017",
    desription:
      "Áo thun trơn, ngắn tay, cổ tròn cùng họa tiết Ananas Typo in 2D và 3D kết hợp ở giữa áo. Phom dáng cổ điển và linh hoạt, thích hợp cho cả Nam và Nữ.",
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [{ color: "#645d54", href: "" }],
    color: "Bungee Cord",
    price: "269.000 VND",
    images: [
      {
        href: "https://ananas.vn/wp-content/uploads/pro_basictee_ABT00017_1.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_basictee_ABT00017_3.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_basictee_ABT00017_4.jpg",
      },
      {
        href: "https://ananas.vn/wp-content/uploads/pro_basictee_ABT00017_2.jpg",
      },
    ],
    soldout: false,
    category: "top",
  },
  {
    href: "/product-detail/aho0009/",
    type: "",
    name: "Ananas Typo Logo Hoodie",
    id: "AHO0009",
    desription:
      'Với chất liệu nỉ thể thao cao cấp được lựa chọn kĩ lưỡng để phù hợp với thời tiết "lạnh nhẹ" của những ngày cuối năm nhưng không tạo cảm giác bức bí, "Ananas Typo Logo Hoodie" sẽ mang đến một outfit năng động và cá tính dù không cần mix-match cầu kì. Đây là một chiếc áo không thể thiếu trong "hoodie seasion" năm nay.',
    sizes: [" ", "L", "M", "S", "XL"],
    colorsSame: [{ color: "#ffb025", href: "" }],
    color: "Citrus",
    price: "500.000 VND",
    images: [
      { href: "https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0009_1.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0009_2.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0009_3.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0009_5.jpg" },
      { href: "https://ananas.vn/wp-content/uploads/pro_hoodie_AHO0009_4.jpg" },
    ],
    soldout: false,
    category: "top",
  },
];
